version: "3.8"

services:

  hive-metastore:
    image: apache/hive:3.1.3
    container_name: hive-metastore
    environment:
      SERVICE_NAME: metastore
      HIVE_METASTORE_WAREHOUSE_DIR: s3://datalake/warehouse

      AWS_ACCESS_KEY_ID: ${S3_ACCESS_KEY}
      AWS_SECRET_ACCESS_KEY: ${S3_SECRET_KEY}
      AWS_ENDPOINT: ${S3_ENDPOINT}
      AWS_REGION: us-east-1

    ports:
      - "9083:9083"

    networks:
      - dlh-net


  trino:
    environment:
      S3_ACCESS_KEY: ${S3_ACCESS_KEY}
      S3_SECRET_KEY: ${S3_SECRET_KEY}
      S3_ENDPOINT: ${S3_ENDPOINT}
    image: trinodb/trino:latest
    container_name: trino
    ports:
      - "8080:8080"

    volumes:
    - ./trino/catalog:/etc/trino/catalog
    - ./trino/filesystem:/etc/trino/filesystem

    networks:
      - dlh-net

    depends_on:
      - hive-metastore


networks:
  dlh-net:
    driver: bridge