
fs.native-s3.enabled=true
fs.native-s3.access-key=${ENV:S3_ACCESS_KEY} 
fs.native-s3.secret-key=${ENV:S3_SECRET_KEY}
fs.native-s3.endpoint=${ENV:S3_ENDPOINT}
fs.native-s3.path-style-access=true
# s3.enabled=true
# s3.access-key=1T59WAW1TM38Q0BC3R6J
# s3.secret-key=ZmSCe0EXUKbhf56gx8UdOj7DCBWyy3ZbDVXLjw3C
# s3.endpoint=https://s3.ru1.storage.beget.cloud
# s3.path-style-access=true