# fs.config-files=/etc/trino/filesystem/s3.properties 
coordinator=true
node-scheduler.include-coordinator=true
http-server.http.port=8080
discovery.uri=http://localhost:8080
catalog.management=static

query.max-memory=512MB
query.max-memory-per-node=512MB
